---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  labels:
    app: rss-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rss-site
  template:
    metadata:
      labels:
        app: rss-site
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: rss-reader
          image: nickchase/rss-php-nginx:v1
          ports:
            - containerPort: 88
